---
- name: Mock Service Status Check
  hosts: localhost
  gather_facts: false

  tasks:

    - name: Mock Service Check
      debug:
        msg:
          - "Service: aimlmanagerSG1"
          - "Status : UP"
          - "Version: 2.33.0"

    - name: Mock AKS Pod
      debug:
        msg:
          - "Pod: prd1isheet1zus1-pod1"
          - "Status: Running"
          - "Node: aks-node-01"
